### ISSUE TITLE
Need Required for Input

### ISSUE THREAD

**Issue by selcuktatar** [ozgrozer/tweet-chart#2]
When you enter another link or not link page not working. 

<img width="799" alt="required" src="https://user-images.githubusercontent.com/41347478/112773948-b1c95300-9040-11eb-973b-41b5f051e434.png">

<img width="1260" alt="requ" src="https://user-images.githubusercontent.com/41347478/112774150-66637480-9041-11eb-9f72-a9ecaa8f65fd.png">

I think we can add like this in index.jsx (i am not sure 😄) 
[My Source](https://ej2.syncfusion.com/react/documentation/form-validator/validation-rules/#validation-rules)

````

const validations = {
  empty: [
    {
      rule: 'isLength',
      args: { min: 1 },
      invalidFeedback: 'Please provide a value'
    },
  ],
  url: [
    {
      rule: 'url',
      required: 'https://twitter.com',
      invalidFeedback: 'Please enter a URL'
    }
  ]
}

**Comment by ozgrozer** [comment]
I'm using [RFV](https://github.com/ozgrozer/rfv) as form validation and it uses [Validator.js](https://github.com/validatorjs/validator.js) as string validation.

Check the commits for the fix for this issue.

[bfc37df](https://github.com/ozgrozer/tweet-chart/commit/10d3577a73de75027752235912d808aaa85647b9)
[10d3577](https://github.com/ozgrozer/tweet-chart/commit/b25a6c9b618376c45a52fe469a94afbf3065d7a1)

**Comment by selcuktatar** [comment]
Okey i get it 🔥
